#!/bin/bash
# Sets up Tony Stark Clap Launcher to run automatically at login on macOS.
# Run once: bash setup_autostart.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAUNCHER="$SCRIPT_DIR/clap_launcher.py"
WRAPPER="$SCRIPT_DIR/run.sh"
PLIST="$HOME/Library/LaunchAgents/com.tonystark.claplauncher.plist"

echo "=== Tony Stark Clap Launcher — Auto-start Setup ==="
echo ""

# Find Python (prefers the conda python that has the packages installed)
PYTHON="$(which python3)"
echo "Python: $PYTHON"
echo "Script: $LAUNCHER"
echo ""

# Install Python dependencies
echo "Installing Python dependencies..."
"$PYTHON" -m pip install --quiet sounddevice numpy yt-dlp
echo "Dependencies installed."
echo ""

# Create a shell wrapper that ensures the right Python is used
cat > "$WRAPPER" << WRAPPER_EOF
#!/bin/bash
# Auto-generated by setup_autostart.sh — do not edit manually.

# Try to source conda so the right python/packages are available
for conda_sh in \\
    "\$HOME/anaconda3/etc/profile.d/conda.sh" \\
    "\$HOME/miniconda3/etc/profile.d/conda.sh" \\
    "/opt/anaconda3/etc/profile.d/conda.sh" \\
    "/opt/homebrew/anaconda3/etc/profile.d/conda.sh" \\
    "/opt/miniconda3/etc/profile.d/conda.sh"; do
    if [ -f "\$conda_sh" ]; then
        source "\$conda_sh"
        conda activate base 2>/dev/null
        break
    fi
done

exec "$PYTHON" "$LAUNCHER"
WRAPPER_EOF
chmod +x "$WRAPPER"
echo "Wrapper created: $WRAPPER"

# Create the LaunchAgent plist
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" << PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.tonystark.claplauncher</string>
    <key>ProgramArguments</key>
    <array>
        <string>$WRAPPER</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>5</integer>
    <key>StandardOutPath</key>
    <string>/tmp/tonystark.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/tonystark.log</string>
</dict>
</plist>
PLIST_EOF
echo "LaunchAgent plist created: $PLIST"

# Load (or reload) the LaunchAgent
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"

echo ""
echo "Done! Tony Stark Clap Launcher is now running in the background."
echo "It will start automatically every time you log in."
echo ""
echo "Useful commands:"
echo "  View logs:   tail -f /tmp/tonystark.log"
echo "  Stop:        launchctl unload ~/Library/LaunchAgents/com.tonystark.claplauncher.plist"
echo "  Start:       launchctl load  ~/Library/LaunchAgents/com.tonystark.claplauncher.plist"
echo ""
echo "NOTE: On first run macOS may ask for microphone permission — click Allow."
